/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client;

/**
 * Client main class.
 */
public class Main extends javax.swing.JFrame {
    
    private Client client;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        // create client initializer
        this.client = new Client(this.textArea);
        
        new Thread(() -> {
            // request client id
            this.client.requestClientId();
            
            // start reply handler
            Thread replyHandler = new Thread(TReplyHandler.getInstance(this.client.getClientPort(), this.textArea, this.executedRequestsLabel));
            replyHandler.start();
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        interfaceLabel = new javax.swing.JLabel();
        configPanel = new javax.swing.JPanel();
        iterationsLabel = new javax.swing.JLabel();
        iterationsSpinner = new javax.swing.JSpinner();
        deadlineLabel = new javax.swing.JLabel();
        deadlineSpinner = new javax.swing.JSpinner();
        sendRequestButton = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        textPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        executedRequestsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Client");
        setResizable(false);

        basePanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(55, 55, 55));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.setToolTipText("");
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        interfaceLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        interfaceLabel.setForeground(new java.awt.Color(255, 255, 255));
        interfaceLabel.setText("Client Interface");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(interfaceLabel)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(interfaceLabel)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        basePanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        configPanel.setBackground(new java.awt.Color(65, 65, 65));
        configPanel.setForeground(new java.awt.Color(255, 255, 255));

        iterationsLabel.setForeground(new java.awt.Color(255, 255, 255));
        iterationsLabel.setText("Iterations");

        iterationsSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        deadlineLabel.setForeground(new java.awt.Color(255, 255, 255));
        deadlineLabel.setText("Deadline");

        deadlineSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        sendRequestButton.setBackground(new java.awt.Color(55, 55, 55));
        sendRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        sendRequestButton.setText("Send Request");
        sendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iterationsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iterationsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(deadlineLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deadlineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendRequestButton)
                .addGap(0, 0, 0))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendRequestButton)
                    .addComponent(iterationsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadlineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iterationsLabel)
                    .addComponent(deadlineLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        basePanel.add(configPanel, java.awt.BorderLayout.CENTER);

        displayPanel.setBackground(new java.awt.Color(65, 65, 65));
        displayPanel.setForeground(new java.awt.Color(255, 255, 255));
        displayPanel.setPreferredSize(new java.awt.Dimension(400, 200));

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(55, 55, 55));
        textArea.setColumns(20);
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setFocusable(false);
        textPane.setViewportView(textArea);

        executedRequestsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        executedRequestsLabel.setForeground(new java.awt.Color(255, 255, 255));
        executedRequestsLabel.setText("Executed Requests: 0");

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(textPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(executedRequestsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPanelLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(executedRequestsLabel)
                .addGap(18, 18, 18)
                .addComponent(textPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        basePanel.add(displayPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(basePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequestButtonActionPerformed
        // request pi service
        if (this.client.getClientPort() != 0){
            //new Thread(() -> {
                this.client.requestPiService((Integer)this.iterationsSpinner.getValue(), (Integer)this.deadlineSpinner.getValue());
            //}).start();
        }
        else {
            System.out.println("No id assigned yet");
            this.textArea.append("No id assigned yet\n");
        }
    }//GEN-LAST:event_sendRequestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JPanel configPanel;
    private javax.swing.JLabel deadlineLabel;
    private javax.swing.JSpinner deadlineSpinner;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JLabel executedRequestsLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel interfaceLabel;
    private javax.swing.JLabel iterationsLabel;
    private javax.swing.JSpinner iterationsSpinner;
    private javax.swing.JButton sendRequestButton;
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textPane;
    // End of variables declaration//GEN-END:variables
}
