/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UC1.Consumer;

import java.util.Properties;
import org.apache.log4j.BasicConfigurator;

/**
 *
 * Consumer process class.
 */
public class PConsumer extends javax.swing.JFrame {

    /**
     * Creates new form PConsumer.
     */
    public PConsumer() {
        initComponents();
    }
    
    /**
     * Initializes Consumer thread.
     */
    public static void initConsumer() {
        //BasicConfigurator.configure();
        
        String HOST = "localhost";
        int PORT = 9092;
        
        Properties properties = new Properties();
        String hosts = "";
        for (int i = 0; i < 3; i++) {
            hosts += HOST + ":" + (PORT + i);
            if (i != 2) hosts += ",";
        }
        properties.put("bootstrap.servers", hosts);
        properties.put("key.deserializer", "org.apache.kafka.common.serialization.IntegerDeserializer");
        properties.put("value.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
        properties.put("group.id", "KafkaConsumersGroup");
        
        Thread consumer = new Thread(TConsumer.getInstance(0, properties));
        
        // start consumer
        consumer.start();
        
        try {
            consumer.join();
        } catch (InterruptedException ex) {}
        
        System.out.println("Consumer thread finished");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        displayPanel = new javax.swing.JPanel();
        displayPanelLabel = new javax.swing.JLabel();
        centerDisplayPanel = new javax.swing.JPanel();
        displayCenterPanel = new javax.swing.JPanel();
        consumerConsoleLabel = new javax.swing.JLabel();
        displayTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UC1 Consumer Process");
        setBounds(new java.awt.Rectangle(900, 200, 800, 600));
        setSize(new java.awt.Dimension(800, 600));

        basePanel.setLayout(new java.awt.BorderLayout());

        displayPanel.setBackground(new java.awt.Color(55, 55, 55));

        displayPanelLabel.setBackground(new java.awt.Color(55, 55, 55));
        displayPanelLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayPanelLabel.setForeground(new java.awt.Color(255, 255, 255));
        displayPanelLabel.setText("Display Panel");

        centerDisplayPanel.setBackground(new java.awt.Color(55, 55, 55));
        centerDisplayPanel.setToolTipText("");
        centerDisplayPanel.setLayout(new java.awt.BorderLayout());

        displayCenterPanel.setBackground(new java.awt.Color(65, 65, 65));

        consumerConsoleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        consumerConsoleLabel.setForeground(new java.awt.Color(255, 255, 255));
        consumerConsoleLabel.setText("Consumer Console");

        displayTextField.setEditable(false);
        displayTextField.setBackground(new java.awt.Color(55, 55, 55));
        displayTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayTextField.setForeground(new java.awt.Color(255, 255, 255));
        displayTextField.setFocusable(false);

        javax.swing.GroupLayout displayCenterPanelLayout = new javax.swing.GroupLayout(displayCenterPanel);
        displayCenterPanel.setLayout(displayCenterPanelLayout);
        displayCenterPanelLayout.setHorizontalGroup(
            displayCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayCenterPanelLayout.createSequentialGroup()
                .addGroup(displayCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayCenterPanelLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(consumerConsoleLabel))
                    .addGroup(displayCenterPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        displayCenterPanelLayout.setVerticalGroup(
            displayCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayCenterPanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(consumerConsoleLabel)
                .addGap(58, 58, 58)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        centerDisplayPanel.add(displayCenterPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGroup(displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(centerDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(displayPanelLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(displayPanelLabel)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(displayPanelLabel)
                .addGap(33, 33, 33)
                .addComponent(centerDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        basePanel.add(displayPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(basePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PConsumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PConsumer().setVisible(true);
            }
        });
        
        /* Initialize Consumer thread */
        initConsumer();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Java swing base panel.
     */
    private javax.swing.JPanel basePanel;
    /**
     * Java swing center display panel.
     */
    private javax.swing.JPanel centerDisplayPanel;
    /**
     * Java swing console label.
     */
    private javax.swing.JLabel consumerConsoleLabel;
    /**
     * Java swing display center panel.
     */
    private javax.swing.JPanel displayCenterPanel;
    /**
     * Java swing display panel.
     */
    private javax.swing.JPanel displayPanel;
    /**
     * Java swing display panel label.
     */
    private javax.swing.JLabel displayPanelLabel;
    /**
     * Java swing display text field.
     */
    public static javax.swing.JTextField displayTextField;
    // End of variables declaration//GEN-END:variables
}
