/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Server;

/**
 * Server main class.
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        Thread server = new Thread(TServer.getInstance(receivedRequestsTextArea, processedRequestsTextArea));
        server.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        logsLabel = new javax.swing.JLabel();
        receivedRequestsPanel = new javax.swing.JPanel();
        textPane = new javax.swing.JScrollPane();
        receivedRequestsTextArea = new javax.swing.JTextArea();
        receivedRequestsLabel = new javax.swing.JLabel();
        processedRequestsPanel = new javax.swing.JPanel();
        textPane1 = new javax.swing.JScrollPane();
        processedRequestsTextArea = new javax.swing.JTextArea();
        processedRequestsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);

        basePanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(55, 55, 55));
        headerPanel.setForeground(new java.awt.Color(255, 255, 255));
        headerPanel.setToolTipText("");
        headerPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        logsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logsLabel.setForeground(new java.awt.Color(255, 255, 255));
        logsLabel.setText("Server Logs");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(logsLabel)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(logsLabel)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        basePanel.add(headerPanel, java.awt.BorderLayout.NORTH);

        receivedRequestsPanel.setBackground(new java.awt.Color(65, 65, 65));

        receivedRequestsTextArea.setEditable(false);
        receivedRequestsTextArea.setBackground(new java.awt.Color(55, 55, 55));
        receivedRequestsTextArea.setColumns(20);
        receivedRequestsTextArea.setForeground(new java.awt.Color(255, 255, 255));
        receivedRequestsTextArea.setLineWrap(true);
        receivedRequestsTextArea.setRows(3);
        receivedRequestsTextArea.setFocusable(false);
        textPane.setViewportView(receivedRequestsTextArea);

        receivedRequestsLabel.setForeground(new java.awt.Color(255, 255, 255));
        receivedRequestsLabel.setText("Received Requests");

        javax.swing.GroupLayout receivedRequestsPanelLayout = new javax.swing.GroupLayout(receivedRequestsPanel);
        receivedRequestsPanel.setLayout(receivedRequestsPanelLayout);
        receivedRequestsPanelLayout.setHorizontalGroup(
            receivedRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receivedRequestsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(receivedRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPane, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receivedRequestsLabel))
                .addContainerGap())
        );
        receivedRequestsPanelLayout.setVerticalGroup(
            receivedRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receivedRequestsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(receivedRequestsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPane, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        basePanel.add(receivedRequestsPanel, java.awt.BorderLayout.CENTER);

        processedRequestsPanel.setBackground(new java.awt.Color(65, 65, 65));
        processedRequestsPanel.setForeground(new java.awt.Color(255, 255, 255));
        processedRequestsPanel.setPreferredSize(new java.awt.Dimension(400, 125));

        processedRequestsTextArea.setEditable(false);
        processedRequestsTextArea.setBackground(new java.awt.Color(55, 55, 55));
        processedRequestsTextArea.setColumns(20);
        processedRequestsTextArea.setForeground(new java.awt.Color(255, 255, 255));
        processedRequestsTextArea.setLineWrap(true);
        processedRequestsTextArea.setRows(3);
        processedRequestsTextArea.setFocusable(false);
        textPane1.setViewportView(processedRequestsTextArea);

        processedRequestsLabel.setForeground(new java.awt.Color(255, 255, 255));
        processedRequestsLabel.setText("Processed Requests");

        javax.swing.GroupLayout processedRequestsPanelLayout = new javax.swing.GroupLayout(processedRequestsPanel);
        processedRequestsPanel.setLayout(processedRequestsPanelLayout);
        processedRequestsPanelLayout.setHorizontalGroup(
            processedRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processedRequestsPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(processedRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processedRequestsLabel))
                .addContainerGap())
        );
        processedRequestsPanelLayout.setVerticalGroup(
            processedRequestsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processedRequestsPanelLayout.createSequentialGroup()
                .addComponent(processedRequestsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        basePanel.add(processedRequestsPanel, java.awt.BorderLayout.SOUTH);

        getContentPane().add(basePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel logsLabel;
    private javax.swing.JLabel processedRequestsLabel;
    private javax.swing.JPanel processedRequestsPanel;
    private javax.swing.JTextArea processedRequestsTextArea;
    private javax.swing.JLabel receivedRequestsLabel;
    private javax.swing.JPanel receivedRequestsPanel;
    private javax.swing.JTextArea receivedRequestsTextArea;
    private javax.swing.JScrollPane textPane;
    private javax.swing.JScrollPane textPane1;
    // End of variables declaration//GEN-END:variables
}
